namespace MeetBase
{
    /// <summary>
    /// Global information
    /// </summary>
    public static class GlobalInfo
    {
        /// <summary>
        /// The country data for all of them
        /// </summary>
        public static List<CountryData> CountryData = new() 
        { 
            new("Afghanistan", "93", new() { "AF",  "AFG" }),
            new("Albania", "355", new() { "AL",  "ALB" }),
            new("Algeria", "213", new() { "DZ",  "DZA" }),
            new("American Samoa", "1-684", new() { "AS",  "ASM" }),
            new("Andorra", "376", new() { "AD",  "AND" }),
            new("Angola", "244", new() { "AO",  "AGO" }),
            new("Anguilla", "1-264", new() { "AI",  "AIA" }),
            new("Antarctica", "672", new() { "AQ",  "ATA" }),
            new("Antigua and Barbuda", "1-268", new() { "AG",  "ATG" }),
            new("Argentina", "54", new() { "AR",  "ARG" }),
            new("Armenia", "374", new() { "AM",  "ARM" }),
            new("Aruba", "297", new() { "AW",  "ABW" }),
            new("Australia", "61", new() { "AU",  "AUS" }),
            new("Austria", "43", new() { "AT",  "AUT" }),
            new("Azerbaijan", "994", new() { "AZ",  "AZE" }),
            new("Bahamas", "1-242", new() { "BS",  "BHS" }),
            new("Bahrain", "973", new() { "BH",  "BHR" }),
            new("Bangladesh", "880", new() { "BD",  "BGD" }),
            new("Barbados", "1-246", new() { "BB",  "BRB" }),
            new("Belarus", "375", new() { "BY",  "BLR" }),
            new("Belgium", "32", new() { "BE",  "BEL" }),
            new("Belize", "501", new() { "BZ",  "BLZ" }),
            new("Benin", "229", new() { "BJ",  "BEN" }),
            new("Bermuda", "1-441", new() { "BM",  "BMU" }),
            new("Bhutan", "975", new() { "BT",  "BTN" }),
            new("Bolivia", "591", new() { "BO",  "BOL" }),
            new("Bosnia and Herzegovina", "387", new() { "BA",  "BIH" }),
            new("Botswana", "267", new() { "BW",  "BWA" }),
            new("Brazil", "55", new() { "BR",  "BRA" }),
            new("British Indian Ocean Territory", "246", new() { "IO",  "IOT" }),
            new("British Virgin Islands", "1-284", new() { "VG",  "VGB" }),
            new("Brunei", "673", new() { "BN",  "BRN" }),
            new("Bulgaria", "359", new() { "BG",  "BGR" }),
            new("Burkina Faso", "226", new() { "BF",  "BFA" }),
            new("Burundi", "257", new() { "BI",  "BDI" }),
            new("Cambodia", "855", new() { "KH",  "KHM" }),
            new("Cameroon", "237", new() { "CM",  "CMR" }),
            new("Canada", "1", new() { "CA",  "CAN" }),
            new("Cape Verde", "238", new() { "CV",  "CPV" }),
            new("Cayman Islands", "1-345", new() { "KY",  "CYM" }),
            new("Central African Republic", "236", new() { "CF",  "CAF" }),
            new("Chad", "235", new() { "TD",  "TCD" }),
            new("Chile", "56", new() { "CL",  "CHL" }),
            new("China", "86", new() { "CN",  "CHN" }),
            new("Christmas Island", "61", new() { "CX",  "CXR" }),
            new("Cocos Islands", "61", new() { "CC",  "CCK" }),
            new("Colombia", "57", new() { "CO",  "COL" }),
            new("Comoros", "269", new() { "KM",  "COM" }),
            new("Cook Islands", "682", new() { "CK",  "COK" }),
            new("Costa Rica", "506", new() { "CR",  "CRI" }),
            new("Croatia", "385", new() { "HR",  "HRV" }),
            new("Cuba", "53", new() { "CU",  "CUB" }),
            new("Curacao", "599", new() { "CW",  "CUW" }),
            new("Cyprus", "357", new() { "CY",  "CYP" }),
            new("Czech Republic", "420", new() { "CZ",  "CZE" }),
            new("Democratic Republic of the Congo", "243", new() { "CD",  "COD" }),
            new("Denmark", "45", new() { "DK",  "DNK" }),
            new("Djibouti", "253", new() { "DJ",  "DJI" }),
            new("Dominica", "1-767", new() { "DM",  "DMA" }),
            new("Dominican Republic", "1-809, 1-829, 1-849", new() { "DO",  "DOM" }),
            new("East Timor", "670", new() { "TL",  "TLS" }),
            new("Ecuador", "593", new() { "EC",  "ECU" }),
            new("Egypt", "20", new() { "EG",  "EGY" }),
            new("El Salvador", "503", new() { "SV",  "SLV" }),
            new("Equatorial Guinea", "240", new() { "GQ",  "GNQ" }),
            new("Eritrea", "291", new() { "ER",  "ERI" }),
            new("Estonia", "372", new() { "EE",  "EST" }),
            new("Ethiopia", "251", new() { "ET",  "ETH" }),
            new("Falkland Islands", "500", new() { "FK",  "FLK" }),
            new("Faroe Islands", "298", new() { "FO",  "FRO" }),
            new("Fiji", "679", new() { "FJ",  "FJI" }),
            new("Finland", "358", new() { "FI",  "FIN" }),
            new("France", "33", new() { "FR",  "FRA" }),
            new("French Polynesia", "689", new() { "PF",  "PYF" }),
            new("Gabon", "241", new() { "GA",  "GAB" }),
            new("Gambia", "220", new() { "GM",  "GMB" }),
            new("Georgia", "995", new() { "GE",  "GEO" }),
            new("Germany", "49", new() { "DE",  "DEU" }),
            new("Ghana", "233", new() { "GH",  "GHA" }),
            new("Gibraltar", "350", new() { "GI",  "GIB" }),
            new("Greece", "30", new() { "GR",  "GRC" }),
            new("Greenland", "299", new() { "GL",  "GRL" }),
            new("Grenada", "1-473", new() { "GD",  "GRD" }),
            new("Guam", "1-671", new() { "GU",  "GUM" }),
            new("Guatemala", "502", new() { "GT",  "GTM" }),
            new("Guernsey", "44-1481", new() { "GG",  "GGY" }),
            new("Guinea", "224", new() { "GN",  "GIN" }),
            new("Guinea-Bissau", "245", new() { "GW",  "GNB" }),
            new("Guyana", "592", new() { "GY",  "GUY" }),
            new("Haiti", "509", new() { "HT",  "HTI" }),
            new("Honduras", "504", new() { "HN",  "HND" }),
            new("Hong Kong", "852", new() { "HK",  "HKG" }),
            new("Hungary", "36", new() { "HU",  "HUN" }),
            new("Iceland", "354", new() { "IS",  "ISL" }),
            new("India", "91", new() { "IN",  "IND" }),
            new("Indonesia", "62", new() { "ID",  "IDN" }),
            new("Iran", "98", new() { "IR",  "IRN" }),
            new("Iraq", "964", new() { "IQ",  "IRQ" }),
            new("Ireland", "353", new() { "IE",  "IRL" }),
            new("Isle of Man", "44-1624", new() { "IM",  "IMN" }),
            new("Israel", "972", new() { "IL",  "ISR" }),
            new("Italy", "39", new() { "IT",  "ITA" }),
            new("Ivory Coast", "225", new() { "CI",  "CIV" }),
            new("Jamaica", "1-876", new() { "JM",  "JAM" }),
            new("Japan", "81", new() { "JP",  "JPN" }),
            new("Jersey", "44-1534", new() { "JE",  "JEY" }),
            new("Jordan", "962", new() { "JO",  "JOR" }),
            new("Kazakhstan", "7", new() { "KZ",  "KAZ" }),
            new("Kenya", "254", new() { "KE",  "KEN" }),
            new("Kiribati", "686", new() { "KI",  "KIR" }),
            new("Kosovo", "383", new() { "XK",  "XKX" }),
            new("Kuwait", "965", new() { "KW",  "KWT" }),
            new("Kyrgyzstan", "996", new() { "KG",  "KGZ" }),
            new("Laos", "856", new() { "LA",  "LAO" }),
            new("Latvia", "371", new() { "LV",  "LVA" }),
            new("Lebanon", "961", new() { "LB",  "LBN" }),
            new("Lesotho", "266", new() { "LS",  "LSO" }),
            new("Liberia", "231", new() { "LR",  "LBR" }),
            new("Libya", "218", new() { "LY",  "LBY" }),
            new("Liechtenstein", "423", new() { "LI",  "LIE" }),
            new("Lithuania", "370", new() { "LT",  "LTU" }),
            new("Luxembourg", "352", new() { "LU",  "LUX" }),
            new("Macau", "853", new() { "MO",  "MAC" }),
            new("Macedonia", "389", new() { "MK",  "MKD" }),
            new("Madagascar", "261", new() { "MG",  "MDG" }),
            new("Malawi", "265", new() { "MW",  "MWI" }),
            new("Malaysia", "60", new() { "MY",  "MYS" }),
            new("Maldives", "960", new() { "MV",  "MDV" }),
            new("Mali", "223", new() { "ML",  "MLI" }),
            new("Malta", "356", new() { "MT",  "MLT" }),
            new("Marshall Islands", "692", new() { "MH",  "MHL" }),
            new("Mauritania", "222", new() { "MR",  "MRT" }),
            new("Mauritius", "230", new() { "MU",  "MUS" }),
            new("Mayotte", "262", new() { "YT",  "MYT" }),
            new("Mexico", "52", new() { "MX",  "MEX" }),
            new("Micronesia", "691", new() { "FM",  "FSM" }),
            new("Moldova", "373", new() { "MD",  "MDA" }),
            new("Monaco", "377", new() { "MC",  "MCO" }),
            new("Mongolia", "976", new() { "MN",  "MNG" }),
            new("Montenegro", "382", new() { "ME",  "MNE" }),
            new("Montserrat", "1-664", new() { "MS",  "MSR" }),
            new("Morocco", "212", new() { "MA",  "MAR" }),
            new("Mozambique", "258", new() { "MZ",  "MOZ" }),
            new("Myanmar", "95", new() { "MM",  "MMR" }),
            new("Namibia", "264", new() { "NA",  "NAM" }),
            new("Nauru", "674", new() { "NR",  "NRU" }),
            new("Nepal", "977", new() { "NP",  "NPL" }),
            new("Netherlands", "31", new() { "NL",  "NLD" }),
            new("Netherlands Antilles", "599", new() { "AN",  "ANT" }),
            new("New Caledonia", "687", new() { "NC",  "NCL" }),
            new("New Zealand", "64", new() { "NZ",  "NZL" }),
            new("Nicaragua", "505", new() { "NI",  "NIC" }),
            new("Niger", "227", new() { "NE",  "NER" }),
            new("Nigeria", "234", new() { "NG",  "NGA" }),
            new("Niue", "683", new() { "NU",  "NIU" }),
            new("North Korea", "850", new() { "KP",  "PRK" }),
            new("Northern Mariana Islands", "1-670", new() { "MP",  "MNP" }),
            new("Norway", "47", new() { "NO",  "NOR" }),
            new("Oman", "968", new() { "OM",  "OMN" }),
            new("Pakistan", "92", new() { "PK",  "PAK" }),
            new("Palau", "680", new() { "PW",  "PLW" }),
            new("Palestine", "970", new() { "PS",  "PSE" }),
            new("Panama", "507", new() { "PA",  "PAN" }),
            new("Papua New Guinea", "675", new() { "PG",  "PNG" }),
            new("Paraguay", "595", new() { "PY",  "PRY" }),
            new("Peru", "51", new() { "PE",  "PER" }),
            new("Philippines", "63", new() { "PH",  "PHL" }),
            new("Pitcairn", "64", new() { "PN",  "PCN" }),
            new("Poland", "48", new() { "PL",  "POL" }),
            new("Portugal", "351", new() { "PT",  "PRT" }),
            new("Puerto Rico", "1-787, 1-939", new() { "PR",  "PRI" }),
            new("Qatar", "974", new() { "QA",  "QAT" }),
            new("Republic of the Congo", "242", new() { "CG",  "COG" }),
            new("Reunion", "262", new() { "RE",  "REU" }),
            new("Romania", "40", new() { "RO",  "ROU" }),
            new("Russia", "7", new() { "RU",  "RUS" }),
            new("Rwanda", "250", new() { "RW",  "RWA" }),
            new("Saint Barthelemy", "590", new() { "BL",  "BLM" }),
            new("Saint Helena", "290", new() { "SH",  "SHN" }),
            new("Saint Kitts and Nevis", "1-869", new() { "KN",  "KNA" }),
            new("Saint Lucia", "1-758", new() { "LC",  "LCA" }),
            new("Saint Martin", "590", new() { "MF",  "MAF" }),
            new("Saint Pierre and Miquelon", "508", new() { "PM",  "SPM" }),
            new("Saint Vincent and the Grenadines", "1-784", new() { "VC",  "VCT" }),
            new("Samoa", "685", new() { "WS",  "WSM" }),
            new("San Marino", "378", new() { "SM",  "SMR" }),
            new("Sao Tome and Principe", "239", new() { "ST",  "STP" }),
            new("Saudi Arabia", "966", new() { "SA",  "SAU" }),
            new("Senegal", "221", new() { "SN",  "SEN" }),
            new("Serbia", "381", new() { "RS",  "SRB" }),
            new("Seychelles", "248", new() { "SC",  "SYC" }),
            new("Sierra Leone", "232", new() { "SL",  "SLE" }),
            new("Singapore", "65", new() { "SG",  "SGP" }),
            new("Sint Maarten", "1-721", new() { "SX",  "SXM" }),
            new("Slovakia", "421", new() { "SK",  "SVK" }),
            new("Slovenia", "386", new() { "SI",  "SVN" }),
            new("Solomon Islands", "677", new() { "SB",  "SLB" }),
            new("Somalia", "252", new() { "SO",  "SOM" }),
            new("South Africa", "27", new() { "ZA",  "ZAF" }),
            new("South Korea", "82", new() { "KR",  "KOR" }),
            new("South Sudan", "211", new() { "SS",  "SSD" }),
            new("Spain", "34", new() { "ES",  "ESP" }),
            new("Sri Lanka", "94", new() { "LK",  "LKA" }),
            new("Sudan", "249", new() { "SD",  "SDN" }),
            new("Suriname", "597", new() { "SR",  "SUR" }),
            new("Svalbard and Jan Mayen", "47", new() { "SJ",  "SJM" }),
            new("Swaziland", "268", new() { "SZ",  "SWZ" }),
            new("Sweden", "46", new() { "SE",  "SWE" }),
            new("Switzerland", "41", new() { "CH",  "CHE" }),
            new("Syria", "963", new() { "SY",  "SYR" }),
            new("Taiwan", "886", new() { "TW",  "TWN" }),
            new("Tajikistan", "992", new() { "TJ",  "TJK" }),
            new("Tanzania", "255", new() { "TZ",  "TZA" }),
            new("Thailand", "66", new() { "TH",  "THA" }),
            new("Togo", "228", new() { "TG",  "TGO" }),
            new("Tokelau", "690", new() { "TK",  "TKL" }),
            new("Tonga", "676", new() { "TO",  "TON" }),
            new("Trinidad and Tobago", "1-868", new() { "TT",  "TTO" }),
            new("Tunisia", "216", new() { "TN",  "TUN" }),
            new("Turkey", "90", new() { "TR",  "TUR" }),
            new("Turkmenistan", "993", new() { "TM",  "TKM" }),
            new("Turks and Caicos Islands", "1-649", new() { "TC",  "TCA" }),
            new("Tuvalu", "688", new() { "TV",  "TUV" }),
            new("U.S. Virgin Islands", "1-340", new() { "VI",  "VIR" }),
            new("Uganda", "256", new() { "UG",  "UGA" }),
            new("Ukraine", "380", new() { "UA",  "UKR" }),
            new("United Arab Emirates", "971", new() { "AE",  "ARE" }),
            new("United Kingdom", "44", new() { "GB",  "GBR" }),
            new("United States", "1", new() { "US",  "USA" }),
            new("Uruguay", "598", new() { "UY",  "URY" }),
            new("Uzbekistan", "998", new() { "UZ",  "UZB" }),
            new("Vanuatu", "678", new() { "VU",  "VUT" }),
            new("Vatican", "379", new() { "VA",  "VAT" }),
            new("Venezuela", "58", new() { "VE",  "VEN" }),
            new("Vietnam", "84", new() { "VN",  "VNM" }),
            new("Wallis and Futuna", "681", new() { "WF",  "WLF" }),
            new("Western Sahara", "212", new() { "EH",  "ESH" }),
            new("Yemen", "967", new() { "YE",  "YEM" }),
            new("Zambia", "260", new() { "ZM",  "ZMB" }),
            new("Zimbabwe", "263", new() { "ZW",  "ZWE" })
        };
    }
}
